name = "blog-platform"
compatibility_date = "2024-01-15"

# 👇👇👇 必须加上这一行，开启 Node.js 兼容模式，否则登录会报错 500 👇👇👇
compatibility_flags = ["nodejs_compat"]

# 指定 Pages 的构建输出目录
pages_build_output_dir = "public"

# 数据库绑定
[[d1_databases]]
binding = "DB"
database_name = "blog-db"
database_id = "ed3f0184-09c4-41af-8d56-ea2d5cd42e79"
